{{- range $name, $opt := .Values.cp }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: {{ $name }}
spec:
  backend: shared
  {{ if $opt }}
  {{ if $opt.pch }}
  postCreateHook: {{ $opt.pch  }}
  {{ end }}
  type: {{ $opt.type | default "k8s" }}
  {{ else }}
  type: "k8s"
  {{ end }}


# {{ if $opt.statusaddon }}
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: install-status-addon
#   namespace: {{ $name }}-system
# spec:
#   template:
#     # This is the pod template
#     spec:
#       initContainers:
#       - name: wait-managedclusteraddons
#         image: quay.io/kubestellar/kubectl:1.27.8
#         command: ['sh', '-c' ]
#         args:
#         - |
#           echo "Waiting for managedclusteraddons..."
#           while [ "$(kubectl api-resources | grep managedclusteraddons 2> /dev/null)" == "" ] ; do
#             echo -n "."
#             sleep 1
#           done
#           echo "done"
#         env:
#         - name: KUBECONFIG
#           value: "/etc/kube/config-incluster"
#         volumeMounts:
#         - name: kubeconfig
#           mountPath: "/etc/kube"
#           readOnly: true
#       containers:
#       - name: install-status-addon
#         image: quay.io/kubestellar/helm:3.14.0
#         args:
#           - upgrade
#           - --install
#           - status-addon
#           - oci://ghcr.io/kubestellar/ocm-status-addon-chart
#           - --version
#           - {{ $opt.statusaddon.version }}
#           - --namespace
#           - open-cluster-management
#         env:
#         - name: HELM_CONFIG_HOME
#           value: "/tmp"
#         - name: HELM_CACHE_HOME
#           value: "/tmp"
#         - name: KUBECONFIG
#           value: "/etc/kube/config-incluster"
#         volumeMounts:
#         - name: kubeconfig
#           mountPath: "/etc/kube"
#           readOnly: true
#       volumes:
#       - name: kubeconfig
#         secret:
#           secretName: vc-vcluster
#       restartPolicy: OnFailure
# {{ end }}


{{- end }}
