{{- if eq (toString .Values.pch.kubestellar) "true" }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: kubestellar
  labels:
    kflex.kubestellar.io/cptype: wds
spec:
  templates:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: "{{.Namespace}}-{{.HookName}}"
    rules:
    - nonResourceURLs:
      - /metrics
      verbs:
      - get
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
    - apiGroups:
      - tenancy.kflex.kubestellar.org
      resources:
      - controlplanes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - tenancy.kflex.kubestellar.org
      resources:
      - controlplanes/status
      verbs:
      - get
      - patch
      - update
    - apiGroups:
      - authentication.k8s.io
      resources:
      - tokenreviews
      verbs:
      - create
    - apiGroups:
      - authorization.k8s.io
      resources:
      - subjectaccessreviews
      verbs:
      - create
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - clusterroles
      - clusterrolebindings
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - roles
      - rolebindings
      verbs:
      - get
      - list
      - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: "{{.Namespace}}-{{.HookName}}"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: "{{.Namespace}}-{{.HookName}}"
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: "{{.Namespace}}"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: "{{.HookName}}"
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - coordination.k8s.io
      resources:
      - leases
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - ""
      resources:
      - events
      - secrets
      - services
      verbs:
      - create
      - patch
      - update
    - apiGroups:
      - ""
      resources:
      - serviceaccounts
      verbs:
      - get
      - create
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - get
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - get
      - create
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - roles
      - rolebindings
      verbs:
      - create
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: "{{.HookName}}"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: "{{.HookName}}"
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: "{{.Namespace}}"
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{.HookName}}"
    spec:
      template:
        spec:
          containers:
          - name: "{{.HookName}}"
            image: quay.io/kubestellar/helm:3.14.0
            imagePullPolicy: IfNotPresent
            args:
              - upgrade
              - --install
              - -n
              - "{{.Namespace}}"
              - kubestellar
              - oci://ghcr.io/kubestellar/kubestellar/kubestellar-operator-chart
              - --version
              - "0.20.0-alpha.1"
              - --set
              - "ControlPlaneName={{.ControlPlaneName}}"
            env:
            - name: XDG_CACHE_HOME
              value: /tmp/helm/.cache
          restartPolicy: Never
      backoffLimit: 1
{{- end }}

{{- if eq (toString .Values.pch.ocm) "true" }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: ocm
  labels:
    kflex.kubestellar.io/cptype: imbs
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{.HookName}}"
    spec:
      template:
        spec:
          containers:
          - name: "{{.HookName}}"
            image: quay.io/kubestellar/clusteradm:0.7.2
            args:
            - init
            env:
            - name: KUBECONFIG
              value: "/etc/kube/config-incluster"
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true
          volumes:
          - name: kubeconfig
            secret:
              secretName: vc-vcluster
          restartPolicy: Never
      backoffLimit: 1
{{- end }}
